name: riverxilee-launcher
base: core22
version: '0.0.0'
summary: RiverXILee Launcher
description: |
  RiverXILee Launcher, a Liquid Glass derivative edition of SJMCL.

grade: stable
confinement: strict

apps:
  riverxilee-launcher:
    command: usr/bin/riverxilee-launcher
    desktop: usr/share/applications/riverxilee-launcher.desktop
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: "1"
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - x11
      - network
      - network-bind
      - opengl
      - audio-playback
      - removable-media
      - home

parts:
  riverxilee-launcher-payload:
    plugin: dump
    source: snap-payload
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libcanberra-gtk3-module

  cleanup:
    after:
      - riverxilee-launcher-payload
    plugin: nil
    build-snaps:
      - core22
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204"; do
        cd "/snap/$snap/current"
        find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
